[general]
import = ["~/.config/alacritty/env.toml", "~\\AppData\\Roaming\\alacritty\\env.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black   = '#1d1f21'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#e6c547'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#70c0ba'
white   = '#373b41'

[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#282a2e'

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[colors.cursor]
text = '#1d1f21'
cursor = '#ffffff'

[cursor]
style = "Block"
unfocused_hollow = true


[env]
TERM = "xterm-256color"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
