# vi mode config for macOS

# v: begin selection
bind-key -T copy-mode-vi 'v' send -X begin-selection

# space: halfpage down
bind-key -T copy-mode-vi 'Space' send -X halfpage-down

# back space: halfpage up
bind-key -T copy-mode-vi 'Bspace' send -X halfpage-up

# C-v: toggle rectangle selection mode
bind-key -T copy-mode-vi C-v send -X rectangle-toggle

# y: copy selected text
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

#p: paste buffer text
bind-key -T copy-mode-vi p run "pbpaste | tmux load-buffer - && tmux paste-buffer"

