# To enable this functions, tpm is required
# For more details, see https://github.com/tmux-plugins/tpm

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Automatically save and restore session
set -g @continuum-boot 'off'
set -g @continuum-restore 'on'
set -g @continuum-save-interval 'off'

# Run plugin
run-shell '~/.tmux/plugins/tpm/tpm'

