# Max history limit on each pane
set -g history-limit 5000

# Configure tmux to eliminate the delay after pressing the Escape key
set -s escape-time 0

# The duration (in milliseconds) that pane numbers are displayed when the display-panes command is executed
set -g display-panes-time 3000

# Start numbering windows and panes from 1
set -g base-index 1
set -g pane-base-index 1

# Automatically renumber windows when a window is closed
set -g renumber-windows on

# Enable autoread
set-option -g focus-events on

# Enable automatic window renaming
setw -g automatic-rename on
set-window-option -g aggressive-resize on

# Enable wm window titles
set -g set-titles on

# WM window title string (uses status bar variables)
set -g set-titles-string "tmux[#S:#I/#{session_windows}:#W]"

