#!/bin/sh

if [ $# -ge 1 ]; then
    OUTPUT="$1"
else
    OUTPUT="${HOME}/.xmonad/xmonad-x86_64-linux"
fi

exec stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$OUTPUT"
