source $HOME/.config/zsh/zinit.zsh
source $HOME/.config/zsh/general.zsh
source $HOME/.config/zsh/env.zsh
typeset -U path

for f in $HOME/.config/zsh/init/*.zsh; do source $f; done
for f in $HOME/.config/zsh/init/env/*.zsh; do source $f; done

if [ -n "$TMUX" ]; then
    for f in $HOME/.config/zsh/tmux/*.zsh; do source $f; done
else
    prompt redhat
fi
