#!/bin/sh

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"
export PATH=$HOME/.local/bin:$PATH
export ADW_DISABLE_PORTAL=1
export QT_QPA_PLATFORMTHEME=gtk
export QT_STYLE_OVERRIDE=Adwaita-Dark
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
export DefaltIMModule=fcitx
export SDL_IM_MODULE=fcitx

systemctl restart --user redshift
picom &
lxqt-policykit-agent &
xremap ~/.config/xremap/config.yml --watch &
volctl &
trayer --edge top --align right \
  --widthtype percent --heighttype pixel \
  --SetDockType true --SetPartialStrut false \
  --expand false \
  --width 8 --height 23 \
  --transparent true --alpha 0 --tint 0x000000 \
  --monitor primary &
