#!/bin/sh

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"
export PATH=$HOME/.local/bin:$PATH
export ADW_DISABLE_PORTAL=1
export QT_QPA_PLATFORMTHEME=gtk
export QT_STYLE_OVERRIDE=Adwaita-Dark
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
export DefaltIMModule=fcitx
export SDL_IM_MODULE=fcitx

systemctl restart --user redshift
