modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
  - name: Henkan-Muhenkan
    remap:
      Alt_L:
        held: Alt_L
        alone: Muhenkan
        alone_timeout_millis: 200
      Alt_R:
        held: Alt_R
        alone: Henkan
        alone_timeout_millis: 200

keymap:
  - name: EmacsBase
    application:
      not: [Alacritty]
    remap:
      C-p: { with_mark: up }
      C-n: { with_mark: down }
      C-h: backspace
  - name: EmacsAdvanced
    application:
      not: [jetbrains-studio, Alacritty]
    remap:
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-a: { with_mark: home }
      C-e: { with_mark: end }
      C-m: enter
  - name: Mac
    remap:
      M-a: [C-a, { set_mark: false }]
      M-z: [C-z, { set_mark: false }]
      M-x: [C-x, { set_mark: false }]
      M-c: [C-c, { set_mark: false }]
      M-v: [C-v, { set_mark: false }]
      M-f: [C-f, { set_mark: false }]
